cmake_minimum_required(VERSION 3.30)
project(Leetcode)

set(CMAKE_CXX_STANDARD 14)

add_executable(Leetcode main.cpp
        Running_of_1D_array_1480.cpp
        Richest_Customer_Wealth_1672.cpp
        Fizz_Buzz_412.cpp
        Number_of_Steps_to_Reduce_a_Number_to_Zero_1342.cpp
        Middle_of_The_Linked_List_876.cpp
        Ransom_Note_383.cpp
        Unique_Binary_Search_Trees_II_95.cpp
        Max_Consecutive_Ones_485.cpp
        Find_Numbers_with_Even_Number_of_Digits_1295.cpp
        Squares_of_a_Sorted_Array_977.cpp
        Duplicate_Zeros_1089.cpp
        Merge_Sorted_Array_88.cpp
        Remove_Element_27.cpp)
